parameters:

    #
    # Factories
    #
    elcodi.factory.comment.class: Elcodi\Component\Comment\Factory\CommentFactory
    elcodi.factory.vote.class: Elcodi\Component\Comment\Factory\VoteFactory

    #
    # Services
    #
    elcodi.comment_manager.class: Elcodi\Component\Comment\Services\CommentManager
    elcodi.comment_parser.class: Elcodi\Component\Comment\Services\CommentParser
    elcodi.comment_cache.class: Elcodi\Component\Comment\Services\CommentCache
    elcodi.comment_vote_manager.class: Elcodi\Component\Comment\Services\VoteManager

    #
    # Controllers
    #
    elcodi.controller.comment.class: Elcodi\Component\Comment\Controller\CommentController

    #
    # EventListeners
    #
    elcodi.event_listener.comment_cache_invalidation.class: Elcodi\Component\Comment\EventListener\CommentCacheInvalidationEventListener

    #
    # EventDispatchers
    #
    elcodi.event_dispatcher.comment.class: Elcodi\Component\Comment\EventDispatcher\CommentEventDispatcher
