services:

    #
    # Controllers
    #
    elcodi.controller.comment:
        class: %elcodi.controller.comment.class%
        arguments:
            - @elcodi.manager.comment
            - @elcodi.comment_cache
            - @elcodi.repository.comment
