services:

    #
    # EventListeners
    #
    elcodi.event_dispatcher.comment:
        class: %elcodi.event_dispatcher.comment.class%
        arguments:
            event_dispatcher: @event_dispatcher
