services:

    #
    # EventListeners
    #
    elcodi.event_listener.comment_cache_invalidation:
        class: %elcodi.event_listener.comment_cache_invalidation.class%
        arguments:
            - @elcodi.comment_cache
        tags:
            - { name: kernel.event_listener, event: comment.onadd, method: onCommentChange, priority: 0 }
            - { name: kernel.event_listener, event: comment.onedit, method: onCommentChange, priority: 0 }
            - { name: kernel.event_listener, event: comment.onremove, method: onCommentChange, priority: 0 }
            - { name: kernel.event_listener, event: comment.onvoted, method: onCommentChange, priority: 0 }
