services:

    #
    # EventListeners
    #
    elcodi.core.comment.event_dispatcher.comment_event_dispatcher:
        class: %elcodi.core.comment.event_dispatcher.comment_event_dispatcher.class%
        arguments:
            event_dispatcher: @event_dispatcher

    elcodi.comment_event_dispatcher:
        alias: elcodi.core.comment.event_dispatcher.comment_event_dispatcher
