services:

    #
    # Factories
    #

    #
    # Factory for entity comment
    #
    elcodi.factory.comment:
        class: %elcodi.factory.comment.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.comment.class%"]]

    #
    # Factory for entity vote
    #
    elcodi.factory.comment_vote:
        class: %elcodi.factory.vote.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.comment_vote.class%"]]
