services:

    #
    # Object Managers
    #
    elcodi.object_manager.comment:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.comment.entity.comment.class% ]

    elcodi.object_manager.vote:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.comment.entity.vote.class% ]
