services:

    #
    # Object Managers
    #
    elcodi.object_manager.comment:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            cart_namespace: %elcodi.core.comment.entity.comment.class%

    elcodi.object_manager.vote:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            cart_namespace: %elcodi.core.comment.entity.vote.class%
