services:

    #
    # Repositories
    #

    #
    # Repository for entity comment
    #
    elcodi.repository.comment:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.comment.entity.comment.class% ]

    #
    # Repository for entity vote
    #
    elcodi.repository.vote:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.comment.entity.vote.class% ]
