services:

    #
    # Repositories
    #

    #
    # Repository for entity comment
    #
    elcodi.core.comment.repository.comment:
        class: %elcodi.core.comment.repository.comment.class%
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.comment.entity.comment.class%

    elcodi.repository.comment:
        alias: elcodi.core.comment.repository.comment
