services:

    #
    # Services
    #
    elcodi.manager.comment:
        class: %elcodi.manager.comment.class%
        arguments:
            - @elcodi.event_dispatcher.comment
            - @elcodi.director.comment
            - @elcodi.comment_parser

    elcodi.comment_parser:
        class: %elcodi.comment_parser.class%
        arguments:
            - @elcodi.comment_parser_adapter

    elcodi.comment_parser_adapter:
        class: Elcodi\Component\Core\Adapter\Parser\Interfaces\ParserAdapterInterface
        synthetic: true

    elcodi.comment_cache:
        class: %elcodi.comment_cache.class%
        arguments:
            - @elcodi.repository.comment
            - @elcodi.manager.comment_vote
            - %elcodi.comment.cache_key%
        calls:
            - [setCache, [@doctrine_cache.providers.elcodi_comments]]
            - [setEncoder, [@elcodi.json_encoder]]

    elcodi.manager.comment_vote:
        class: %elcodi.manager.comment_vote.class%
        arguments:
            - @elcodi.event_dispatcher.comment
            - @elcodi.director.comment_vote
