parameters:

    #
    # MarkdownParser Adapter
    #
    elcodi.core.comment.adapter.markdown_parser_adapter.class: Elcodi\Component\Comment\Adapter\Parser\MarkdownParserAdapter

services:

    #
    # MarkdownParser Adapter
    #
    elcodi.core.comment.adapter.markdown_parser_adapter:
        class: %elcodi.core.comment.adapter.markdown_parser_adapter.class%

    elcodi.core.comment.adapter.parser_adapter:
        alias: elcodi.core.comment.adapter.markdown_parser_adapter
